-- Forge: global exercise library seed.
-- Run after 0001_init.sql. Safe to re-run (uses ON CONFLICT on lower(name)).

insert into public.exercises (name, primary_muscle, secondary_muscles, equipment, instructions, is_custom)
values
  ('Barbell Back Squat', 'quads', '{glutes,hamstrings,core}', 'barbell',
    'Set the bar across your upper traps. Brace your core, sit back through the hips, and drive up through mid-foot.', false),
  ('Front Squat', 'quads', '{glutes,core}', 'barbell',
    'Rack the bar in the front-rack position. Keep elbows high and descend with a vertical torso.', false),
  ('Goblet Squat', 'quads', '{glutes,core}', 'dumbbell',
    'Hold a dumbbell vertically at chest height. Squat between your feet keeping elbows inside knees.', false),
  ('Bulgarian Split Squat', 'quads', '{glutes,hamstrings}', 'dumbbell',
    'Elevate the rear foot. Lower the back knee toward the floor while keeping the front shin nearly vertical.', false),
  ('Walking Lunge', 'quads', '{glutes,hamstrings}', 'dumbbell',
    'Step forward into a lunge, drive off the front leg, and step through into the next rep.', false),
  ('Leg Press', 'quads', '{glutes,hamstrings}', 'machine',
    'Place feet shoulder-width on the platform. Lower under control until knees track over toes, then press.', false),
  ('Leg Extension', 'quads', '{}', 'machine',
    'Extend the knees fully against the pad. Squeeze the quads at the top and lower with control.', false),
  ('Romanian Deadlift', 'hamstrings', '{glutes,back}', 'barbell',
    'Hinge at the hips with a soft knee bend. Lower the bar along the legs until you feel a hamstring stretch.', false),
  ('Conventional Deadlift', 'back', '{glutes,hamstrings,core}', 'barbell',
    'Brace, pull the slack out of the bar, then drive the floor away keeping the bar against your body.', false),
  ('Sumo Deadlift', 'glutes', '{quads,back}', 'barbell',
    'Adopt a wide stance with feet flared. Brace, then drive the knees out as you stand.', false),
  ('Hip Thrust', 'glutes', '{hamstrings}', 'barbell',
    'Sit with shoulder blades on a bench, bar across the hips. Drive through the heels and lock out at the top.', false),
  ('Glute Bridge', 'glutes', '{hamstrings,core}', 'bodyweight',
    'Lie on your back with knees bent. Press through the heels and squeeze the glutes hard at the top.', false),
  ('Lying Leg Curl', 'hamstrings', '{}', 'machine',
    'Curl the heels toward your glutes against the pad. Lower under control.', false),
  ('Seated Calf Raise', 'calves', '{}', 'machine',
    'Drive the balls of the feet down, pause at the top, then lower into a full stretch.', false),
  ('Standing Calf Raise', 'calves', '{}', 'machine',
    'Press through the balls of the feet to full plantar flexion, hold, then lower under control.', false),
  ('Bench Press', 'chest', '{triceps,shoulders}', 'barbell',
    'Plant your feet, set a small arch, lower the bar to the lower chest, and press up over the shoulders.', false),
  ('Incline Bench Press', 'chest', '{shoulders,triceps}', 'barbell',
    'On a 30-45° incline, lower the bar to the upper chest, then press to lockout.', false),
  ('Dumbbell Bench Press', 'chest', '{triceps,shoulders}', 'dumbbell',
    'Press the dumbbells from the chest until they meet over the shoulders. Lower slowly into a stretch.', false),
  ('Incline Dumbbell Press', 'chest', '{shoulders,triceps}', 'dumbbell',
    'On a moderate incline, press dumbbells from the upper chest to lockout overhead.', false),
  ('Push-Up', 'chest', '{triceps,core}', 'bodyweight',
    'Brace your core in a tight plank. Lower until your chest is just above the floor, then press up.', false),
  ('Cable Fly', 'chest', '{shoulders}', 'cable',
    'Set the cables high. Sweep the handles down and together with a slight bend in the elbows.', false),
  ('Pec Deck', 'chest', '{}', 'machine',
    'Hug the pads together with a slight bend in the elbows, squeezing the chest at the contraction.', false),
  ('Pull-Up', 'back', '{biceps,core}', 'bodyweight',
    'Hang from a bar with a pronated grip. Pull until your chin clears the bar, then lower with control.', false),
  ('Chin-Up', 'back', '{biceps}', 'bodyweight',
    'Use a supinated grip. Pull until your chin clears the bar, focusing on driving the elbows down.', false),
  ('Lat Pulldown', 'back', '{biceps}', 'cable',
    'Pull the bar toward the upper chest, leading with the elbows. Squeeze the lats and control the return.', false),
  ('Seated Cable Row', 'back', '{biceps,forearms}', 'cable',
    'Sit tall, pull the handle to the lower ribs, squeeze the shoulder blades, then extend with control.', false),
  ('Barbell Row', 'back', '{biceps,core}', 'barbell',
    'Hinge to ~45°. Row the bar to the lower chest while keeping the torso fixed.', false),
  ('Dumbbell Row', 'back', '{biceps}', 'dumbbell',
    'Brace one hand on a bench. Row the dumbbell to the hip, keeping the elbow close to the body.', false),
  ('T-Bar Row', 'back', '{biceps}', 'barbell',
    'Hinge forward and row the handle to your sternum, keeping a neutral spine.', false),
  ('Face Pull', 'shoulders', '{back}', 'cable',
    'Pull the rope toward the face, leading with the elbows. Externally rotate at the end of the pull.', false),
  ('Overhead Press', 'shoulders', '{triceps,core}', 'barbell',
    'Brace and press the bar overhead in a vertical path, finishing with arms locked under the bar.', false),
  ('Seated Dumbbell Shoulder Press', 'shoulders', '{triceps}', 'dumbbell',
    'Press dumbbells from shoulder height to overhead lockout without flaring the ribs.', false),
  ('Arnold Press', 'shoulders', '{triceps}', 'dumbbell',
    'Start with palms facing you. Rotate the dumbbells as you press overhead.', false),
  ('Lateral Raise', 'shoulders', '{}', 'dumbbell',
    'Raise the dumbbells out to the sides until elbows reach shoulder height. Lower under control.', false),
  ('Rear Delt Fly', 'shoulders', '{back}', 'dumbbell',
    'Hinge forward, then raise the dumbbells out to the sides with a soft elbow bend.', false),
  ('Barbell Curl', 'biceps', '{forearms}', 'barbell',
    'Keep elbows pinned to your sides. Curl the bar to shoulder height and lower with control.', false),
  ('Dumbbell Curl', 'biceps', '{forearms}', 'dumbbell',
    'Curl one or both dumbbells while keeping the elbow stationary. Squeeze hard at the top.', false),
  ('Hammer Curl', 'biceps', '{forearms}', 'dumbbell',
    'Use a neutral grip. Curl the dumbbells while keeping the wrists locked.', false),
  ('Preacher Curl', 'biceps', '{}', 'cable',
    'Anchor the upper arm on a pad. Curl through a full range, controlling the eccentric.', false),
  ('Triceps Pushdown', 'triceps', '{}', 'cable',
    'Pin elbows to your sides. Extend the elbows fully, then return to a 90° bend.', false),
  ('Overhead Triceps Extension', 'triceps', '{}', 'dumbbell',
    'Hold a dumbbell overhead. Lower behind the head, then extend the elbows back to lockout.', false),
  ('Skullcrusher', 'triceps', '{}', 'barbell',
    'Lower the bar toward the forehead by bending the elbows, then extend to lockout.', false),
  ('Close-Grip Bench Press', 'triceps', '{chest,shoulders}', 'barbell',
    'Use a shoulder-width grip. Tuck elbows and press the bar to lockout to bias the triceps.', false),
  ('Plank', 'core', '{full_body}', 'bodyweight',
    'Hold a rigid plank position with the glutes squeezed and the ribs tucked.', false),
  ('Hanging Leg Raise', 'core', '{}', 'bodyweight',
    'Hang from a bar. Raise the legs to parallel (or higher), then lower under control.', false),
  ('Cable Crunch', 'core', '{}', 'cable',
    'Kneel below a high cable, rope behind the head. Crunch by curling the spine toward the hips.', false),
  ('Russian Twist', 'core', '{}', 'bodyweight',
    'Sit with knees bent, lean back. Rotate side to side, tapping the floor with each rep.', false),
  ('Farmer Carry', 'core', '{forearms,full_body}', 'dumbbell',
    'Carry heavy dumbbells with proud posture for distance or time.', false),
  ('Kettlebell Swing', 'glutes', '{hamstrings,core}', 'kettlebell',
    'Hinge and explode through the hips to swing the kettlebell to shoulder height.', false),
  ('Box Jump', 'quads', '{glutes,calves}', 'bodyweight',
    'Drop into a quarter squat and jump onto a box, landing softly with bent knees.', false),
  ('Burpee', 'full_body', '{cardio}', 'bodyweight',
    'Drop to a push-up, return to standing, and finish with a small jump and clap overhead.', false),
  ('Running', 'cardio', '{full_body}', 'other',
    'Sustain a steady aerobic pace. Track distance, time, or interval pace as appropriate.', false),
  ('Cycling', 'cardio', '{quads,glutes}', 'other',
    'Cycle steady-state or in intervals. Track distance, time, and resistance.', false),
  ('Rowing Machine', 'cardio', '{back,quads}', 'machine',
    'Drive with the legs, lean back, then pull with the arms. Reverse the order on the return.', false)
on conflict do nothing;
